"""Generation of the predictions of a model on a Spider split."""

import json
from pathlib import Path
from typing import TypedDict

from tqdm import tqdm
from transformers import PreTrainedModel, PreTrainedTokenizerBase

from text2sql.data import Sample
from text2sql.model import generate_batch
from text2sql.prompt import build_prompt


class PredictionCounts(TypedDict):
    """How many predictions a generation run made."""

    generated: int  # predictions generated by this run
    already_done: int  # predictions that were already in the file


def generate_predictions(
    model: PreTrainedModel,
    tokenizer: PreTrainedTokenizerBase,
    samples: list[Sample],
    predictions_path: Path,
    batch_size: int,
) -> PredictionCounts:
    """Generates a prediction for every question and appends it to a file.

    Args:
        model (PreTrainedModel): Model from `load_model`.
        tokenizer (PreTrainedTokenizerBase): Tokenizer from `load_model`.
        samples (list[Sample]): Questions to answer.
        predictions_path (Path): Predictions file.
        batch_size (int): Questions generated at once.

    Returns:
        PredictionCounts: Predictions generated and predictions already in the file.
    """
    predictions_path.parent.mkdir(exist_ok=True)
    done = (
        {json.loads(line)["id"] for line in predictions_path.read_text().splitlines()}
        if predictions_path.exists()
        else set()
    )

    conversations = {i: build_prompt(sample) for i, sample in enumerate(samples) if i not in done}
    todo = sorted(conversations, key=lambda i: sum(len(m["content"]) for m in conversations[i]))

    with (
        predictions_path.open("a") as file,
        tqdm(total=len(samples), initial=len(done)) as progress,
    ):
        for start in range(0, len(todo), batch_size):
            batch = todo[start : start + batch_size]
            replies = generate_batch(model, tokenizer, [conversations[i] for i in batch])
            for i, predicted in zip(batch, replies):
                file.write(
                    json.dumps({"id": i, "db_id": samples[i]["db_id"], "predicted": predicted})
                    + "\n"
                )
            file.flush()
            progress.update(len(batch))
    return PredictionCounts(generated=len(todo), already_done=len(done))
